[tool.poetry]
name = "agentbrowserv3"
version = "0.1.0"
description = ""
authors = ["AiWaldoh <kevin@gptcoder.pro>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.0.1"
nltk = "^3.8.1"
colorlog = "^6.8.2"
pyyaml = "^6.0.1"
requests = "^2.32.3"
playwright = "^1.44.0"
colorama = "^0.4.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
